### ISSUE TITLE
Hmmm

### ISSUE THREAD

**Issue by darkdarcool** [JBYT27/Idiots-Guide-to-Github#2]
When are you gonna work on this?

**Comment by JBYT27** [comment]
@darkdarcool, well as of rn, im kinda busy with school and stuff, so prob in a few months or weeks lol

**Comment by darkdarcool** [comment]
woah ok

**Comment by JBYT27** [comment]
Oops, I meant summer lol sry

**Comment by darkdarcool** [comment]
Wdym by summer

**Comment by JBYT27** [comment]
Uh, by school I meant summer

**Comment by darkdarcool** [comment]
Ohhhh ok
